### ISSUE TITLE
LinkedList Insert complexity

### ISSUE THREAD

**Issue by nesterov-n** [MindorksOpenSource/android-interview-questions#31]
LinkedList has O(1) complexity only on insertions to a head of the list. Insertions to middle causes traversal that takes O(n)

**Comment by josias1991** [comment]
@nesterov-n i think this is incorrect, i could be wrong though, but to my understanding is that when inserting to a LinkedList, the insert operation itself is O(1) but it may take O(n) to get to the position to insert in. Usually when calculating insertions, it is usually assumed that you are already in the position to insert the item, so the insertion in fact is just O(1).
