### ISSUE TITLE
Suggestion on writing style

### ISSUE THREAD

**Issue by vjs3** [MindorksOpenSource/android-interview-questions#34]
This is a very useful repository with lots of views on daily basis.

Hence I would suggest increasing readability, it would be great if change questions to bold and keep answers in the normal fonts.

This way it would be easy to distinguish between the two especially with the increase in text size, it will make it much easier for users to read.

**Comment by amitshekhariitbhu** [comment]
Yes, feedback taken.

**Comment by jukov** [comment]
I think would be better if android questions will be grouped by themes (e.g. Intents, Fragments, NDKs etc).
I can make it if you agree.

**Comment by amitshekhariitbhu** [comment]
@jukov Agree. I will welcome.
